### ISSUE TITLE
Värit

### ISSUE THREAD

**Issue by Miconen** [AhmedGitt/OKP1#8]

**Comment by Miconen** [comment]
https://coolors.co/58355e-e03616-fff689-cfffb0-5998c5

**Comment by Rosalise** [comment]
![värit](https://user-images.githubusercontent.com/112698878/198521819-3126d93e-fd39-4888-b741-e32c1b8a10c1.jpeg)

**Comment by Miconen** [comment]
#a17864
#624645
#381e1d
